name: CI

on:
  pull_request:

jobs:
  run_tests:
    name: Run Tests
    strategy:
      matrix:
        day: [day01, day02]
    uses: ./.github/workflows/test-day.yml
    with:
      day: ${{ matrix.day }} 
